name: deploy to gh-pages pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.6.1'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint
      continue-on-error: false  # Fail the workflow if linting errors occur


    # - name: Run tests
    #   run: npm test
    #   continue-on-error: false  # Fail the workflow if tests fail

    - name: Build
      run: npm run build

    - name: Set up Git for deployment
      run: |
        git config --global user.email "fifa.ajay219@gmail.com"
        git config --global user.name "apoorv-x12"
        
    - name: Deploy
      run: |
        npm run deploy
      env:
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Use the secret here


  # format:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  
